development:
  adapter: postgresql
  encoding: utf8
  database: santa_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: santa_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: santa_production
  pool: 5
  username:
  password:
