:queues:
 - [default, 1]
 - [mailers, 2]
 - santa_default
 - santa_mailers

:max_retries: 1

common: &default
  :concurrency: <%= ((((ENV.fetch("RAILS_MAX_THREADS") { 5 }).to_i * (ENV.fetch("WEB_CONCURRENCY") { 1 }).to_i) || 5) * 0.8).to_i %>
development:
  <<: *default
test:
  <<: *default
staging:
  <<: *default
production:
  <<: *default
